project:
  type: website

bibliography: assets/references.bib
csl: assets/apa.csl


website:
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Transition** - This page will become the handbook for ISE starting in February 2026."
    type: primary
    position: below-navbar

  title: "ISE Lab Handbook"
  favicon: assets/favicon.ico
  site-url: https://fs-ise.github.io/handbook/
  repo-url: https://github.com/fs-ise/handbook
  repo-actions: [edit, issue]
  navbar:
    logo: assets/logo.png
    right:
      - text: "Overview"
        href: index.qmd
      - text: "Teaching"
        href: teaching/index.qmd
      - text: "Research"
        href: research/index.qmd
      - text: "Management"
        href: management/index.qmd
      - text: "Team"
        href: team/index.qmd
      - text: "Contribute"
        href: contribute.qmd
      - text: '{{< iconify octicon:mark-github-16 title="GitHub" label="GitHub" >}}'
        href: "https://github.com/fs-ise/handbook"

  sidebar:
    - title: "Research"
      style: floating
      search: true
      contents:
        - research/index.qmd
        - research/author_copies.qmd
        - research/talks.qmd
        - research/publications.qmd
        - research/SOP.qmd
        - research/analysis_templates.qmd
        - research/author_copies.qmd
        - research/collaboration.qmd
        - research/data_management.qmd
        - research/dissemination.qmd
        - research/ethics.qmd
        - research/goals.qmd
        - research/ideas.qmd
        - research/improvement.qmd
        - research/index.qmd
        - research/labs.qmd
        - research/literature_review.qmd
        - research/mailing_lists.qmd
        - research/methods.qmd
        - research/outlets.qmd
        - research/paper_templates.qmd
        - research/phyton.qmd
        - research/presentation.qmd
        - research/publication.qmd
        - research/publications.qmd
        - research/repo setup.qmd
        - research/research_support_tasks.qmd
        - research/revision.qmd
        - research/selection.qmd
        - research/submission.qmd
        - research/survey.qmd
        - research/systems.qmd
        - research/talks.qmd
        - research/writing.qmd


    - title: "Teaching"
      style: floating
      contents:
        - teaching/index.qmd

        - section: "Courses"
          contents:
            # - teaching/seminars.qmd
            # - teaching/projects.qmd
            - teaching/lectures.qmd
            - teaching/theses.qmd

        - section: "Design"
          contents:
            - text: "Systems"
              href: teaching/systems.qmd
            - teaching/new.qmd
            - teaching/univis.qmd
            - teaching/quarto.qmd
            - teaching/pedagogy.qmd
            - teaching/teaching_materials.qmd
            - teaching/improvements.qmd

        - section: "Delivery"
          contents:
            - teaching/lms.qmd
            - teaching/evaluations.qmd
            - teaching/dissemination.qmd

        - section: "Assessment"
          contents:
            - teaching/flexnow.qmd
            - teaching/exams.qmd
            - teaching/certificates.qmd
            - teaching/plagiarism.qmd
            - teaching/reviews.qmd

        - section: "Student Support"
          contents:
            - teaching/counselling.qmd
            - teaching/recommendations.qmd
            - teaching/stipends_and_awards.qmd

        - section: "Institutional"
          contents:

            - teaching/platforms_degree_programs_courses.qmd
            - teaching/department.qmd
            - teaching/rankings.qmd

    - title: "Management"
      contents:
        - management/index.qmd

        - section: "Communication"
          contents:
            - management/mail.qmd
            - management/website.qmd
            - management/faculty.qmd
            - management/media_kit.qmd

        - section: "Infrastructure"
          contents:
            - management/controlling.qmd
            - management/sys_admin.qmd

        - section: "Teaching"
          contents:
            - management/ext_lecturers.qmd
            - management/course_organization.qmd
            - management/course_scheduling.qmd
            - management/certificates.qmd
            - management/lufv_reports.qmd
            - management/exams.qmd
            - management/theses.qmd
            - management/reports.qmd
            - management/new_modules.qmd


        - section: "Research"
          contents:
            - management/library.qmd
            - management/travel.qmd
            - management/publications.qmd
            - management/research_support.qmd
            - management/visitors.qmd

        - section: "Risk management"
          contents:
            - management/compliance.qmd
            - management/emergencies.qmd
            - management/security.qmd

        - section: "Procurement"
          contents:
            - management/orders.qmd
            - management/reimbursements.qmd

        - section: "HR"
          contents:
            - management/hiring.qmd
            - management/contracts.qmd
            - management/onboarding.qmd
            - management/sick_leave.qmd
            - management/vacation.qmd
            - management/offboarding.qmd

    - title: "Team"
      contents:
        - team/index.qmd

    - title: "Contributing"
      contents:
        - contribute.qmd

format:
  html:
    theme: cosmo
    css: assets/styles.css
    toc: true
    toc-depth: 3
    code-fold: true
    smooth-scroll: true
    grid:
      body-width: 1000px

extensions:
  iconify:
    style: "color: #002EFF;"

execute:
  freeze: auto

