project:
  type: website

bibliography: assets/references.bib
csl: assets/apa.csl


website:
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Transition** - This page will become the handbook for ISE starting in February 2026."
    type: primary
    position: below-navbar

  title: "ISE Lab Handbook"
  favicon: assets/favicon.ico
  site-url: https://fs-ise.github.io/handbook/
  repo-url: https://github.com/fs-ise/handbook
  repo-actions: [edit, issue]
  navbar:
    logo: assets/logo.png
    right:
      - text: "Overview"
        href: index.qmd
      - text: "Teaching"
        href: teaching/index.qmd
      - text: "Research"
        href: research/index.qmd
      - text: "Management"
        href: management/index.qmd
      - text: "Academy"
        href: academy/index.qmd
      - text: "Team"
        href: team/index.qmd
      - text: '{{< iconify octicon:mark-github-16 title="GitHub" label="GitHub" >}}'
        href: "https://github.com/fs-ise/handbook"

  sidebar:
    - title: "Research"
      style: floating
      search: true
      contents:
        - research/index.qmd
        - section: "Objectives"
          contents:
            - research/statement.qmd
            - research/SOP.qmd
          
        - section: "Research context"
          contents:
            - research/mailing_lists.qmd
            - research/labs.qmd

        - section: "Projects"
          contents:
            - research/projects.qmd
            - research/improvement.qmd

        - section: "Funding"
          contents:
          - research/funding_overview.qmd

        - section: "Methods"
          contents:
          - research/methods.qmd
          - research/systems.qmd
          - research/literature_review.qmd
          - research/survey.qmd
          - research/data_management.qmd
          - research/data_sets.qmd
          - research/repo_setup.qmd
          - research/analysis_templates.qmd
          - research/phyton.qmd

        - section: "Writing"
          contents:
          - research/outlets.qmd
          - research/pdf_collection.qmd
          - research/knowledge_management.qmd
          - research/collaboration.qmd
          - research/writing_technical.qmd
          - research/writing_conceptual.qmd
          - research/revision.qmd
          - research/submission.qmd
          - research/presentation.qmd
          - research/publication.qmd
          - research/dissemination.qmd

        - section: "Community service"
          contents:
          - research/peer_review.qmd
          - research/editorial_work.qmd

        - section: "Output"
          contents:
          - research/data.qmd
          - research/software.qmd
          - research/publications.qmd
          - research/talks.qmd


    - title: "Teaching"
      style: floating
      contents:
        - teaching/index.qmd

        - section: "Objectives"
          contents:
            - teaching/statement.qmd

        - section: "Courses"
          contents:
            - teaching/course_overview.qmd
            - teaching/theses.qmd

        - section: "Design"
          contents:
            - teaching/new_course.qmd
            - text: "Systems"
              href: teaching/systems.qmd
            - teaching/pedagogy.qmd
            - teaching/materials.qmd
            - teaching/knowledge_management.qmd
            - teaching/improvements.qmd

        - section: "Delivery"
          contents:
            - teaching/lms.qmd
            - teaching/evaluations.qmd
            - teaching/advertising.qmd

        - section: "Assessment"
          contents:
            - teaching/exams.qmd
            - teaching/certificates.qmd
            - teaching/plagiarism.qmd
            - teaching/reviews.qmd

        - section: "Student Support"
          contents:
            - teaching/counselling.qmd
            - teaching/recommendations.qmd
            - teaching/stipends_and_awards.qmd

        - section: "Institutional"
          contents:
            - teaching/platforms_degree_programs_courses.qmd
            - teaching/rankings.qmd
            - teaching/department.qmd
            - teaching/reports.qmd

        - section: "Output"
          contents:
            - teaching/publications.qmd
            - teaching/oer.qmd

    - title: "Management"
      contents:
        - management/index.qmd
        - management/transition.qmd

        - section: "Objectives"
          contents:
            - management/statement.qmd
            - management/responsibilities.qmd
            - management/sop.qmd
            - management/agendas.qmd
            - management/planning_review_sessions.qmd

        - section: "Communication"
          contents:
            - management/mail.qmd
            - management/website.qmd
            - management/faculty.qmd
            - management/media_kit.qmd

        - section: "Infrastructure"
          contents:
            - management/handbook.qmd
            - management/repositories.qmd
            - management/systems_overview.qmd
            - management/controlling.qmd
            - management/systems_administration.qmd
            - management/resources.qmd
            - management/archive.qmd

        - section: "Support"
          contents:
            - management/research_support.qmd
            - management/teaching_support.qmd

        - section: "Risk management"
          contents:
            - management/compliance.qmd
            - management/emergencies.qmd
            - management/security.qmd

        - section: "Procurement"
          contents:
            - management/orders.qmd
            - management/reimbursements.qmd

        - section: "HR"
          contents:
            - management/hiring.qmd
            - management/onboarding.qmd
            - management/travel.qmd
            - management/sick_leave.qmd
            - management/vacation.qmd
            - management/offboarding.qmd

    - title: "Academy"
      contents:
        - academy/index.qmd
        - academy/development.qmd
        - academy/research_training.qmd
        - academy/how_tos.qmd


    - title: "Team"
      contents:
        - team/index.qmd

format:
  html:
    theme:
      light: cosmo
      dark: slate
    dark-mode-toggle: true
    css: assets/styles.css
    toc: true
    toc-depth: 3
    code-fold: true
    smooth-scroll: true
    code-tools: true 
    grid:
      body-width: 1000px
    include-after-body: 
      - assets/scripts/weekend-mode.js
    highlight-style: github
    mermaid-format: svg


extensions:
  iconify:
    style: "color: #002EFF;"

execute:
  freeze: auto


filters:
  - custom-callout

custom-callout:
  resource:
    title: "Resource"
    icon: true
    icon-symbol: "üîó"
    color: "#0d6efd"
  confidential:
    title: "Confidential"
    icon: true
    icon-symbol: "üîí"
    color: "#dc3545"
  objective:
    title: "Objective"
    icon: true
    icon-symbol: "üéØ"
    color: "#0d6efd"
  self-service:
    title: "Self-service"
    icon: true
    icon-symbol: "üõ†Ô∏è"
    color: "#198754"

nextcloud:
  grades: "https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/files/69?dir=/10-lab/14_grades"
  archive: "https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/files?dir=/10-lab/19_archive&fileid=62"
  theses: "https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/files/124?dir=/30-teaching/35_theses"
  publications: "https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/?dir=/20-20-research/29_publications&fileid=1264"
  recommendations: "https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/files/20128?dir=/30-teaching/30_processes/70_recommendations"
  travel: "https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/?dir=/10-lab/13_travel&fileid=61"
  projects: "https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/files/88094?dir=/20-research/25_projects"
  mail_tracker: "https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/?dir=/10-lab/10_processes/51_mail&fileid=8856"
  hiring: "https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/files?dir=/10-lab/11_hr&fileid=58"
  pdf_collection: "https://nc-2272638881871040784.nextcloud-ionos.com/index.php/apps/files/files/373460?dir=/20-research/22_literature"

handbook:
  url: "https://github.com/fs-ise/handbook"