project:
  type: website

bibliography: references.bib
csl: apa.csl


website:
  # announcement: 
  #   icon: info-circle
  #   dismissable: true
  #   content: "**Alert** - this is some information that you should pay attention to"
  #   type: primary
  #   position: below-navbar

  site-url: http://0.0.0.0:4200/
  title: "ISE Lab Handbook"
  favicon: assets/favicon.ico
  navbar:
    logo: assets/logo.png
    left:
      - text: "Overview"
        href: index.qmd
      - text: "Teaching"
        href: teaching/index.qmd
      - text: "Research"
        href: research/index.qmd
      - text: "Management"
        href: management/index.qmd
      - text: "Contribute"
        href: contribute.qmd

  sidebar:
    # Sidebar shown on all research/* pages
    - title: "Research"
      style: "floating"
      search: true
      contents:
        - research/index.qmd      # <- MUST be first and match the navbar href
        - research/vision.qmd
        - research/standards.qmd
        - research/workflows.qmd
        - research/publications.qmd

    # Sidebar shown on all teaching/* pages
    - title: "Teaching"
      contents:
        - teaching/index.qmd      # <- matches navbar href
        - teaching/principles.qmd
        - teaching/materials.qmd
        - teaching/courses.qmd

    # Sidebar shown on all management/* pages
    - title: "Management"
      contents:
        - management/index.qmd    # <- matches navbar href
        - management/communication.qmd
        - management/meetings.qmd
        - management/tools.qmd
        - management/checklists.qmd

    # Sidebar for the contribute page
    - title: "Contributing"
      contents:
        - contribute.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    code-fold: true
    smooth-scroll: true
    grid:
      body-width: 1000px


execute:
  freeze: auto

