project:
  type: website

bibliography: references.bib
csl: apa.csl


website:
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Transition** - This page will become the primary handbook for ISE starting in February 2026."
    type: primary
    position: below-navbar

  site-url: http://0.0.0.0:4200/
  title: "ISE Lab Handbook"
  favicon: assets/favicon.ico
  navbar:
    logo: assets/logo.png
    left:
      - text: "Overview"
        href: index.qmd
      - text: "Teaching"
        href: teaching/index.qmd
      - text: "Research"
        href: research/index.qmd
      - text: "Management"
        href: management/index.qmd
      - text: "Contribute"
        href: contribute.qmd

  sidebar:
    - title: "Research"
      style: "floating"
      search: true
      contents:
        - research/index.qmd
        - research/publications.qmd

    - title: "Teaching"
      contents:
        - teaching/index.qmd
        - teaching/quarto.qmd
        - teaching/courses.qmd

    - title: "Management"
      contents:
        - management/index.qmd
        - management/checklists.qmd

    - title: "Contributing"
      contents:
        - contribute.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    code-fold: true
    smooth-scroll: true
    grid:
      body-width: 1000px


execute:
  freeze: auto

